### ISSUE TITLE
dupe ids example is passing

### ISSUE THREAD

**Issue by turbomam** [turbomam/examples-first-cookiecutter#17]
**After generation of the repo**, in `src/data/examples/invalid/PersonCollection-dupe-ids.yaml`

with

```yaml
entries:
  - id: example:Person001
    name: foo bar
  - id: example:Person001
    name: foo bar
```

----

```shell
make test
```

> ValueError: Counter example src/data/examples/invalid/PersonCollection-dupe-ids.yaml succeeded validation
> make: *** [Makefile:138: examples/output] Error 1
