### ISSUE TITLE
are undefined prefixes supposed to pass?

### ISSUE THREAD

**Issue by turbomam** [turbomam/examples-first-cookiecutter#51]
```yaml
entries:
  - id: undefined:Person001
    name: foo bar
  - id: undefined:Person002
    name: foo bar
```
